FutureRealty.PL/Areas/Dashboard/Controllers/PortfoliosController.cs
using AutoMapper;
using FutureRealty.DAL.Data;
using FutureRealty.DAL.Models;
using FutureRealty.PL.Areas.Dashboard.ViewModels;
using FutureRealty.PL.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FutureRealty.PL.Areas.Dashboard.Controllers
{
    [Authorize(Roles = "Admin")]

    [Area("Dashboard")]
    public class PortfoliosController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public PortfoliosController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            
            return View(mapper.Map<IEnumerable<PortfoliosVM>>(context.Portfolios.ToList()));

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(PortfolioFormVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
           

            var Portfolio = mapper.Map<Portfolio>(vm);
            context.Add(Portfolio);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));


        }
        [HttpGet]
        public IActionResult Details(int id)
        {

            var Portfolio = context.Portfolios
              .Include(p => p.Items)
              .AsNoTracking()
              .FirstOrDefault(p => p.Id == id);


            if (Portfolio == null)
            {
                return NotFound();
            }

            var ViewModel = mapper.Map<PortfolioDetailsVM>(Portfolio);
            return View(mapper.Map<PortfolioDetailsVM>(ViewModel));
        }
        public IActionResult Delete(int id)
        {
            var Portfolio = context.Portfolios.Find(id);
            if (Portfolio is null)
            {
                return NotFound();
            }

            return View(mapper.Map<PortfoliosVM>(Portfolio));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var Portfolio = context.Portfolios
                .Include(p => p.Items)
                .AsNoTracking()
                .FirstOrDefault(p => p.Id == id);

            if (Portfolio is null)
            {
                return RedirectToAction(nameof(Index));
            }
           
            var ViewModel = mapper.Map<PortfoliosVM>(Portfolio);
            if (ViewModel.Items.Any())
            {
                return View("DeleteWithItems", ViewModel);
            }

            context.Portfolios.Remove(Portfolio);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var Portfolio = context.Portfolios.Find(id);
            if (Portfolio is null)
            {
                return NotFound();
            }

            var PortfolioVm = mapper.Map<PortfolioFormVM>(Portfolio);

            return View(PortfolioVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PortfolioFormVM vm)
        {
            var Portfolio = context.Portfolios.Find(vm.Id);
            if (Portfolio is null)
            {
                return NotFound();
            }


            if (!ModelState.IsValid)
            {
                return View(vm);
            }

        

            mapper.Map(vm, Portfolio);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }



    }
}

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/Create.cshtml
@model PortfolioFormVM

@section Header {
     Portfolio
}

<div class="col-md-12">


    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create</h3>
        </div>


        <form asp-controller="Portfolios" asp-action="Create">
            @Html.AntiForgeryToken()
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name">Portfolio name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter the neme">
                </div>

                


            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/Delete.cshtml
@model PortfoliosVM

@section Header {
    Delete Portfolio
}

<div class="col-md-12">
    <div class="card card-danger">
        <div class="card-header">
            <h3 class="card-title">Delete Confirmation</h3>
        </div>
        <div class="card-body">
            <p>Are you sure you want to delete @Model.Name Portfolio?</p>
        </div>
        <div class="card-footer">
            <form asp-controller="Portfolios" asp-action="Delete">
                @Html.AntiForgeryToken()
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-controller="Portfolios" asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/DeleteWithItems.cshtml
@model PortfoliosVM

@section Header {
    Delete Portfolio
}
<div>
<p>Portfolio Name: @Model.Name</p>
<br>
<p>You must delete all associated items before deleting this portfolio.</p>
<br>


<h3>Associated Items:</h3>
<ul>
    @foreach (var item in Model.Items)
    {
        <li>"@item.Name "</li> 
    }
</ul>
</div>

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/Details.cshtml
@model PortfolioDetailsVM

@section Header {
    Portfolio Details
}

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Details for @Model.Name</h3>
        </div>
        <ul>
            
            <li> Status : @(Model.IsDeleted ? "Deleted" : "Active")</li>
            <li> Created : @Model.CreatedAt </li>
            <li> Items :
            <ul>
                @foreach (var item in Model.Items)
                {
                        <li>"@item.Name : @Html.Raw(item.Description) "</li>
                }
            </ul>
                </li>
            
        </ul>
    </div>
</div>

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/Edit.cshtml
@model PortfolioFormVM
Portfolio
@section Header {
     Edit Portfolios
}

<div class="col-md-12">


    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit</h3>
        </div>


        <form asp-controller="Portfolios" asp-action="Edit">
            @Html.AntiForgeryToken()
            <div class="card-body">
                

                <input type="hidden" aasp-for="Id">
                <div class="form-group">
                    <label asp-for="Name">Service name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter the neme">
                </div>

            

                <div class="form-group">
                    <label asp-for="IsDeleted">@(Model.IsDeleted ? "The status is Deleted , do you want let it like this ?" : "The status is Active , Do you want to delete it?")</label>
                    <input asp-for="IsDeleted">
                    <span>yes</span>
                </div>
             

            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

FutureRealty.PL/Areas/Dashboard/Views/Portfolios/Index.cshtml
@model IEnumerable<PortfoliosVM>



@section Header {
     Portfolios
}

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Portfolios Table</h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered" id="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            
                            <td>
                                <a asp-controller="Portfolios" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Edit</a>
                                <a asp-controller="Portfolios" asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a>
                                <a asp-controller="Portfolios" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                       
                    }
                </tbody>
            </table>
        </div>

        
    </div>


</div>